/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("ingredients").del();
  await knex("ingredients").insert([
    { id: 1, ingredient_name: "Spaghetti", category_id: 7 },
    { id: 2, ingredient_name: "Egg", category_id: 3 },
    { id: 3, ingredient_name: "Pancetta", category_id: 1 },
    { id: 4, ingredient_name: "Pecorino Romano Cheese", category_id: 3 },
    { id: 5, ingredient_name: "Black Pepper", category_id: 8 },
    { id: 6, ingredient_name: "Salt", category_id: 8 },
    { id: 7, ingredient_name: "Ground Beef", category_id: 1 },
    { id: 8, ingredient_name: "Bread Crumbs", category_id: 7 },
    { id: 9, ingredient_name: "Parmesan Cheese", category_id: 3 },
    { id: 10, ingredient_name: "Garlic", category_id: 8 },
    { id: 11, ingredient_name: "Milk", category_id: 3 },
    { id: 12, ingredient_name: "Parsley", category_id: 8 },
    { id: 13, ingredient_name: "Canned Tomatoes", category_id: 7 },
    { id: 14, ingredient_name: "Olive Oil", category_id: 10 },
    { id: 15, ingredient_name: "Onion", category_id: 5 },
    { id: 16, ingredient_name: "Pizza Dough", category_id: 11 },
    { id: 17, ingredient_name: "Tomato Sauce", category_id: 9 },
    { id: 18, ingredient_name: "Fresh Mozzarella", category_id: 3 },
    { id: 19, ingredient_name: "Basil", category_id: 8 },
    { id: 20, ingredient_name: "Baguette", category_id: 11 },
    { id: 21, ingredient_name: "Tomato", category_id: 5 },
    { id: 22, ingredient_name: "Balsamic Vinegar", category_id: 9 },
    { id: 23, ingredient_name: "Ground Pork", category_id: 1 },
    { id: 24, ingredient_name: "Tomato Paste", category_id: 9 },
    { id: 25, ingredient_name: "Ricotta Cheese", category_id: 3 },
    { id: 26, ingredient_name: "Lasagna Sheets", category_id: 7 },
    { id: 27, ingredient_name: "Mozzarella Cheese", category_id: 3 },
    { id: 28, ingredient_name: "Chicken Breast", category_id: 1 },
    { id: 29, ingredient_name: "Egg Noodle", category_id: 7 },
    { id: 30, ingredient_name: "Carrot", category_id: 5 },
    { id: 31, ingredient_name: "Celery", category_id: 5 },
    { id: 32, ingredient_name: "Chicken Broth", category_id: 7 },
    { id: 33, ingredient_name: "Butter", category_id: 10 },
    { id: 34, ingredient_name: "Thyme", category_id: 8 },
    { id: 35, ingredient_name: "Bay Leaf", category_id: 8 },
    { id: 36, ingredient_name: "Romaine Lettuce", category_id: 5 },
    { id: 37, ingredient_name: "Croutons", category_id: 7 },
    { id: 38, ingredient_name: "Caesar Dressing", category_id: 9 },
    { id: 39, ingredient_name: "Lemon", category_id: 6 },
    { id: 40, ingredient_name: "Hamburger Bun", category_id: 11 },
    { id: 41, ingredient_name: "Cheddar Cheese", category_id: 3 },
    { id: 42, ingredient_name: "Lettuce", category_id: 5 },
    { id: 43, ingredient_name: "Pickles", category_id: 9 },
    { id: 44, ingredient_name: "Ketchup", category_id: 9 },
    { id: 45, ingredient_name: "Mustard", category_id: 9 },
    { id: 46, ingredient_name: "Mayonnaise", category_id: 9 },
    { id: 47, ingredient_name: "Bread", category_id: 11 },
    { id: 48, ingredient_name: "Avocado", category_id: 5 },
    { id: 49, ingredient_name: "Cherry Tomatoes", category_id: 5 },
    { id: 50, ingredient_name: "Lobster", category_id: 2 },
    { id: 51, ingredient_name: "Heavy Cream", category_id: 3 },
    { id: 52, ingredient_name: "White Wine", category_id: 9 },
    { id: 53, ingredient_name: "Paprika", category_id: 8 },
    { id: 54, ingredient_name: "White Fish", category_id: 2 },
    { id: 55, ingredient_name: "Corn Tortilla", category_id: 11 },
    { id: 56, ingredient_name: "Cabbage", category_id: 5 },
    { id: 57, ingredient_name: "Cilantro", category_id: 8 },
    { id: 58, ingredient_name: "Cumin", category_id: 8 },
    { id: 59, ingredient_name: "Chili Powder", category_id: 8 },
    { id: 60, ingredient_name: "Sour Cream", category_id: 3 },
    { id: 61, ingredient_name: "Lime", category_id: 6 },
    { id: 62, ingredient_name: "Pork Loin", category_id: 1 },
    { id: 63, ingredient_name: "Pineapple", category_id: 6 },
    { id: 64, ingredient_name: "Achiote Paste", category_id: 9 },
    { id: 65, ingredient_name: "Orange Juice", category_id: 6 },
    { id: 66, ingredient_name: "White Vinegar", category_id: 9 },
    { id: 67, ingredient_name: "Oregano", category_id: 8 },
    { id: 68, ingredient_name: "Enchilada Sauce", category_id: 9 },
    { id: 69, ingredient_name: "Rice", category_id: 11 },
    { id: 70, ingredient_name: "Soy Sauce", category_id: 9 },
    { id: 71, ingredient_name: "Green Onion", category_id: 8 },
    { id: 72, ingredient_name: "Peas", category_id: 4 },
    { id: 73, ingredient_name: "Ginger", category_id: 8 },
    { id: 74, ingredient_name: "Sesame Oil", category_id: 10 },
    { id: 75, ingredient_name: "Beef Brisket", category_id: 1 },
    { id: 76, ingredient_name: "Potato", category_id: 5 },
    { id: 77, ingredient_name: "Beef Broth", category_id: 7 },
    { id: 78, ingredient_name: "Noodles", category_id: 11 },
    { id: 79, ingredient_name: "Chili Bean Paste", category_id: 9 },
    { id: 80, ingredient_name: "Sichuan Peppercorn", category_id: 8 },
    { id: 81, ingredient_name: "Chili Oil", category_id: 9 },
    { id: 82, ingredient_name: "Vinegar", category_id: 9 },
    { id: 83, ingredient_name: "Sesame Paste", category_id: 9 },
    { id: 84, ingredient_name: "Sugar", category_id: 7 },
    { id: 85, ingredient_name: "Peanuts", category_id: 7 },
    { id: 86, ingredient_name: "Dried Red Chilies", category_id: 8 },
    { id: 87, ingredient_name: "Oyster Sauce", category_id: 9 },
    { id: 88, ingredient_name: "Rice Vinegar", category_id: 9 },
    { id: 89, ingredient_name: "Cornstarch", category_id: 7 },
    { id: 90, ingredient_name: "Tofu", category_id: 4 },
    { id: 91, ingredient_name: "Soft Tofu", category_id: 4 },
    { id: 92, ingredient_name: "Mussel", category_id: 2 },
    { id: 93, ingredient_name: "Shrimp", category_id: 2 },
    { id: 94, ingredient_name: "Dried Anchovies", category_id: 2 },
    { id: 95, ingredient_name: "Kelp", category_id: 12 },
    { id: 96, ingredient_name: "Water", category_id: 7 },
    { id: 97, ingredient_name: "Aged Kimchi", category_id: 12 },
    { id: 98, ingredient_name: "Pork Belly", category_id: 1 },
    { id: 99, ingredient_name: "Gochugaru", category_id: 8 },
    { id: 100, ingredient_name: "Gochujang", category_id: 9 },
    { id: 101, ingredient_name: "Black Bean Paste", category_id: 9 },
    { id: 102, ingredient_name: "Zucchini", category_id: 5 },
    { id: 103, ingredient_name: "Cooking Oil", category_id: 10 },
    { id: 104, ingredient_name: "Bean Sprouts", category_id: 4 },
    { id: 105, ingredient_name: "Sesame Seeds", category_id: 9 },
    { id: 106, ingredient_name: "Sweet Potato Starch Noodle", category_id: 11 },
    { id: 107, ingredient_name: "Beef", category_id: 1 },
    { id: 108, ingredient_name: "Spinach", category_id: 5 },
    { id: 109, ingredient_name: "Shiitake Mushroom", category_id: 5 },
    { id: 110, ingredient_name: "Pork Cutlet", category_id: 1 },
    { id: 111, ingredient_name: "Flour", category_id: 7 },
    { id: 112, ingredient_name: "Japanese Curry Roux", category_id: 9 },
    { id: 113, ingredient_name: "Miso Paste", category_id: 9 },
    { id: 114, ingredient_name: "Dashi Stock", category_id: 7 },
    { id: 115, ingredient_name: "Ramen Noodle", category_id: 11 },
    { id: 116, ingredient_name: "Chashu Pork", category_id: 1 },
    { id: 117, ingredient_name: "Corn", category_id: 5 },
    { id: 118, ingredient_name: "Nori", category_id: 12 },
    { id: 119, ingredient_name: "Sushi Rice", category_id: 5 },
    { id: 120, ingredient_name: "Salmon Sashimi", category_id: 2 },
    { id: 121, ingredient_name: "Cucumber", category_id: 5 },
    { id: 122, ingredient_name: "Wasabi", category_id: 9 },
    { id: 123, ingredient_name: "Picked Ginger", category_id: 9 },
    { id: 124, ingredient_name: "Okonomiyaki Sauce", category_id: 9 },
    { id: 125, ingredient_name: "Kewpie Mayonnaise", category_id: 9 },
    { id: 126, ingredient_name: "Bonito Flakes", category_id: 9 },
    { id: 127, ingredient_name: "Chicken Thigh", category_id: 1 },
    { id: 128, ingredient_name: "Mirin", category_id: 9 },
  ]);
}
